# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'DataStructuresAndAlgorithms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DataStructuresAndAlgorithms

  pod 'ReactiveObjC'
  pod 'ReactiveObjCBridge'
  
  pod 'Masonry'

end
